<h1>S'inscrire</h1>

 

<!-- Formulaire d'inscription -->

<form action="/users/add" method="post" novalidate>
    <div>
        <label for="input-email">Email :</label>
        <input type="email" name="email" id="input-email">
    </div>
    <div>
        <label for="input-password">Mot de passe :</label>
        <input type="password" name="password" id="input-password">
    </div>
    <div>
        <label for="input-firstname">Prénom :</label>
        <input type="text" name="firstname" id="input-firstname">
    </div>
    <div>
        <label for="input-lastname">Nom :</label>
        <input type="text" name="lastname" id="input-lastname">
    </div>
    <div>
        <label for="input-phone">Téléphone :</label>
        <input type="tel" name="phone_number" id="input-phone">
    </div>
    <div>
        <input type="submit" value="S'inscrire">
    </div>


    <!-- Si l'utilisateur à déja un compte -->
    <p>Vous avez déjà un compte ? <a href="/users/connexion">Connectez-vous</a></p>
    <p>Vous voulez louer vos biens ?</p>
    <label for="">Cochez cette case : </label>
    <input type="checkbox" name="role_id" id="renter" value="9">
</form>



