<h1>S'inscrire</h1>

<div class="nav-barre">
        <nav>
            <ul>
                <li><a href="/">Accueil</a></li>
                <li><a href="/rentals">Locations</a></li>
                <li><a href="/profile">Mon profil</a></li>
                <li><a href="/login">Connexion</a></li>
            </ul>
        </nav>
</div>
 
<form action="">
    <label for="email">Email</label>
    <input type="email" name="email" id="email">
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password">
    <label for="password">Confirmer le mot de passe</label>
    <input type="password" name="password" id="password">
    <button type="submit">S'inscrire</button>
    <p>Vous avez déjà un compte ? <a href="/login/connexion">Connectez-vous</a></p>
    <p>Vous voulez louer vos biens ?</p>
    <label for="">Cochez cette case : </label>
    <input type="checkbox" name="renter" id="renter">
</form>