<h1>Se connecter</h1>

<form action="/users/connexion" method="post">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" required>
    <button type="submit">Se connecter</button>
    <p>Vous n'avez pas de compte ? <a href="/users/add">Inscrivez-vous</a></p>
</form>

