<h1>Se connecter</h1>

<div class="nav-barre">
        <nav>
            <ul>
                <li><a href="/">Accueil</a></li>
                <li><a href="/rentals">Locations</a></li>
                <li><a href="/profile">Mon profil</a></li>
                <li><a href="/login">Connexion</a></li>
            </ul>
        </nav>
</div>

<form action="/login" method="post">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" required>
    <button type="submit">Se connecter</button>
    <p>Vous n'avez pas de compte ? <a href="/login">Inscrivez-vous</a></p>
</form>