
<h1>Havenly</h1>


<div class="vignettes">
    <?php if (isset($logements) && !empty($logements)): ?>
        <?php foreach ($logements as $logement): ?>
            <a href="/rentals/<?php echo urlencode($logement->getId()); ?>" class="vignette-link">
                <div class="vignette">
                    <img src="/image/<?php echo htmlspecialchars($logement->getImage()); ?>" alt="Image du logement">
                    <div class="vignette-content">
                        <h3><?php echo htmlspecialchars(ucfirst($logementRepo->getAdresseById($logement->getAdresseId())['pays']) .',  '.$logementRepo->getAdresseById($logement->getAdresseId())['ville']); ?></h3>
                        <p><?php echo htmlspecialchars($logement->getDescription()); ?></p>
                        <p class="price"><?php echo htmlspecialchars($logement->getPrix()); ?> €</p>
                    </div>
                </div>
            </a>
        <?php endforeach; ?>
    <?php else: ?>
        <p>Aucun logement trouvé.</p>
    <?php endif; ?>
</div>

