<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <title><?php

use App\Controller\SessionController;

 echo $title ?></title>

    
</head>
<body>

<?php

SessionController::start();  // Démarre la session si elle n'est pas déjà active
?>


<div class="navbar">
        <nav>
            <ul>
                <li><a href="/">Accueil</a></li>
                <ul>Profils
                    <li><a href="/profile">Mon profile</a></li>
                    <li><a href="/profile">Mes locations</a></li>
                    <li><a href="/biens">Mes biens</a></li>
                </ul>
                <li><a href="/users/connexion">Connexion</a></li>
            </ul>
        </nav>
</div>
 


